services:
  db:
    image: postgres:16
    container_name: jobtrackr_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtrackr
    ports:
      - "5432:5432"
    volumes:
      - jobtrackr_pg:/var/lib/postgresql/data

  db_test:
    image: postgres:16
    container_name: jobtrackr_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtrackr_test
    ports:
      - "5433:5432"

volumes:
  jobtrackr_pg:
